config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :task_lists

end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
    
    validates :name, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :set_task_list, only: [:show, :edit, :update, :destroy]

  # GET /task_lists
  # GET /task_lists.json
  def index
    @task_lists = TaskList.all
  end

  # GET /task_lists/1
  # GET /task_lists/1.json
  def show()
    @task_list = TaskList.find(params[:id])
  end

  # GET /task_lists/new
  def new
    @task_list = TaskList.new
  end

  # GET /task_lists/1/edit
  def edit
  end

  # POST /task_lists
  # POST /task_lists.json
  def create
    @task_list = TaskList.new(task_list_params)

    respond_to do |format|
      if @task_list.save
        format.html { redirect_to @task_list, notice: 'Task list was successfully created.' }
        format.json { render :show, status: :created, location: @task_list }
      else
        format.html { render :new }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_lists/1
  # PATCH/PUT /task_lists/1.json
  def update
    respond_to do |format|
      if @task_list.update(task_list_params)
        format.html { redirect_to @task_list, notice: 'Task list was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_list }
      else
        format.html { render :edit }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_lists/1
  # DELETE /task_lists/1.json
  def destroy
    @task_list.destroy
    respond_to do |format|
      format.html { redirect_to task_lists_url, notice: 'Task list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_list
      @task_list = TaskList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_list_params
      params.require(:task_list).permit(:name, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index ()
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>

<%= render partial: 'shared/header' %>
  <div class='container'>
    <%= yield %>
  </div>
<%= render partial: 'shared/footer' %>


</body>
</html>

app/views/shared/_footer.html.erb
<div class='container'>
    footer
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
     <!--Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" href="#">Brand</a>-->
      <%= link_to I18n.t('views.application.name', default: 'oTODO'),root_path, class: 'navbar-brand' %>
    </div>

     <!--Collect the nav links, forms, and other content for toggling-->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!--<ul class="nav navbar-nav">-->
      <!--  <li><a href="#">Link <span class="sr-only">(current)</span></a></li>-->
      <!--  <li><a href="#">Link</a></li>-->
      <!--  <li class="dropdown">-->
      <!--    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
      <!--    <ul class="dropdown-menu">-->
      <!--      <li><a href="#">Action</a></li>-->
      <!--      <li><a href="#">Another action</a></li>-->
      <!--      <li><a href="#">Something else here</a></li>-->
      <!--      <li role="separator" class="divider"></li>-->
      <!--      <li><a href="#">Separated link</a></li>-->
      <!--      <li role="separator" class="divider"></li>-->
      <!--      <li><a href="#">One more separated link</a></li>-->
      <!--    </ul>-->
      <!--  </li>-->
      <!--</ul>-->
      <!--<form class="navbar-form navbar-left">-->
      <!--  <div class="form-group">-->
      <!--    <input type="text" class="form-control" placeholder="Search">-->
      <!--  </div>-->
      <!--  <button type="submit" class="btn btn-default">Submit</button>-->
      <!--</form>-->
      <!--<ul class="nav navbar-nav navbar-right">-->
      <!--  <li><a href="#">Link</a></li>-->
      <!--  <li class="dropdown">-->
      <!--    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
      <!--    <ul class="dropdown-menu">-->
      <!--      <li><a href="#">Action</a></li>-->
      <!--      <li><a href="#">Another action</a></li>-->
      <!--      <li><a href="#">Something else here</a></li>-->
      <!--      <li role="separator" class="divider"></li>-->
      <!--      <li><a href="#">Separated link</a></li>-->
      <!--    </ul>-->
      <!--  </li>-->
      <!--</ul>-->
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/task_lists/_form.html.erb
<%= form_for(@task_list) do |f| %>
  <% if @task_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_list.errors.count, "error") %> prohibited this task_list from being saved:</h2>

      <ul>
      <% @task_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_lists/edit.html.erb
<h1>Editing Task List</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_list %> |
<%= link_to 'Back', task_lists_path %>

app/views/task_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Task Lists</h1>

<table class = table>
  <thead>
    <tr>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @task_lists.each do |task_list| %>
      <tr>
        <td><%= task_list.name %></td>
        <td><%= link_to 'Show', task_list %></td>
        <td><%= link_to 'Edit', edit_task_list_path(task_list) %></td>
        <td><%= link_to 'Destroy', task_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task list', new_task_list_path %>

app/views/task_lists/new.html.erb
<h1>New Task List</h1>

<%= render 'form' %>

<%= link_to 'Back', task_lists_path %>

app/views/task_lists/show.html.erb
<p id="notice"><%= notice %></p>

<td>Name:</td>
<td><%= @task_list.name %></td>
</br>
<td >Description: </td>
<td><%= @task_list.description %></td>
</br>
<%= link_to 'Edit', edit_task_list_path(@task_list) %> |
<%= link_to 'Back', task_lists_path %>

app/views/welcome/index.html.erb
<h1>WELCOME TO MY APP</h1>